### ISSUE TITLE
Error Card triggers erroneously

### ISSUE THREAD

**Issue by CuriousJames** [CanterburyMedia/MabelCardPrinter#2]
Upon error events being caught ErrorCard (which determines if there is a card upon which an error has happened) gets triggered when there is no card associated with Error.

For example, if the printer register fails due to a bad status code returned from API error card = {Void manager_ErrorCard(System.Object, MabelCardPrinter.PrinterEventArgs)}

**Comment by naxxfish** [comment]
Event flow for PrinterManager.cs has been changed dramatically, so this bug will have disappeared.
