### ISSUE TITLE
Disable Printer Requirements on Setting

### ISSUE THREAD

**Issue by CuriousJames** [CanterburyMedia/MabelCardPrinter#3]
It would be good if a setting can be added, so the lack of a physically attached printer doesn't stop the testing of the API elements

**Comment by naxxfish** [comment]
Should this be a compile time setting, or an application setting?

**Comment by CuriousJames** [comment]
Wo, what a question.  I think ideally all settings should be application settings.

**Comment by naxxfish** [comment]
Fixed in b8f9252eaf82ea3a6523da45a723e0e3ac3dc87b where, amongst other things, the Don't Print setting causes a card not to be printed. It also does not update it in the database as being printed... which may or may not be the right thing to do.

**Comment by CuriousJames** [comment]
For the record I'd say that's the right thing to do, thanks!
